### ISSUE TITLE
parcels documentation new website

### ISSUE THREAD

**Issue by cjongedijk** [OceanParcels/oceanparcels_website#2]
The old website had a 'parcels documentation' tab, sorted by topic and with links to fragments of the source code. It was not properly updating with the releases and was quite ugly, however it offered a nice quick access to the code and supported quick learning/familiarising for users that wanted to dig deeper then the tutorials (or prefer reading small parts of the code, without having to open the full source code in a project and search in there). Is this coming back in the new website?

**Comment by erikvansebille** [comment]
This has been fixed now with the new 'gh-pages' at http://oceanparcels.org/gh-pages/html/
