### ISSUE TITLE
traffic between notebooks not seen.

### ISSUE THREAD

**Issue by reint-fischer** [OceanParcels/oceanparcels_website#44]
Recently we have added many links between tutorial notebooks and the documentation for a more natural guide on specific parcels topics. We also added Google Analytics event tags to the tutorial tiles on the homepage to see how often people visit the notebooks. These event tags do not cover all the other links however. This is not a major problem but something to be aware of.

**Comment by VeckoTheGecko** [comment]
@erikvansebille no longer relevent? Since notebooks are now on RTD

**Comment by erikvansebille** [comment]
Indeed, can be closed now
