### ISSUE TITLE
Installation process not correct since `parcels_get_examples` script removed

### ISSUE THREAD

**Issue by erikvansebille** [OceanParcels/oceanparcels_website#79]
From Parcels v.2.4.2., there is no more `parcels_get_examples` script, so step 4 of the [installation instructions](https://oceanparcels.org/#installing) needs to be updated. I think it should now be a matter of downloading the zip at [the Tutorial and Documentation page](https://docs.oceanparcels.org/en/latest/_downloads/307c382eb1813dc691e8a80d6c0098f7/parcels_tutorials.zip), right? Can you confirm, @VeckoTheGecko?

**Comment by VeckoTheGecko** [comment]
Yes, thats it

**Comment by erikvansebille** [comment]
OK, but is that link static? https://docs.oceanparcels.org/en/latest/_downloads/307c382eb1813dc691e8a80d6c0098f7/parcels_tutorials.zip seems rather random. I'd rather put the link right on the Installation instructions than point users first to https://docs.oceanparcels.org/en/latest/documentation.html and ask them to click the link. 

Also, for the testing in the coda-forge, we test the peninsula_example; but that would also require downloading it, then? Any way to script the download? Or perhaps is it best to `wget` is directly from the parcels repo on GitHub?

**Comment by VeckoTheGecko** [comment]
> Also, for the testing in the coda-forge, we test the peninsula_example; but that would also require downloading it, then?

Just saw the [recipe](https://github.com/conda-forge/parcels-feedstock/blob/6c9187d90ec1e532460538d528fef5605c32266f/recipe/meta.yaml#L58-L60C51). I think a `wget` from the parcels repo may be easiest. Alternatively could change the test case itself.

> OK, but is that link static?

Doesn't look like it, and I don't think a static one exists. Honestly, I think the whole `Installing Parcels` and `Contributing to Parcels development` sections would be better on RTD anyway.

**Comment by erikvansebille** [comment]
Yes, I agree that we soon need to overhaul the whole oceanparcels.org landing page, moving the installation instructions to docs, the articles to a separate pages, etc. But in the meantime, I suggest to implement #80 so that at least the installation instructions are correct
